### ISSUE TITLE
创建文件夹

### ISSUE THREAD

**Issue by Coffee-kitten** [WishMelz/imgurl#1]
创建文件夹啥时候修复一下呀

**Comment by WishMelz** [comment]
使用自定义目录的时候,规则 `/xxx`  点击确定后,可以直接上传文件.
如果没用上传文件,github仓库是没有这个目录的,列表页面会报错.

**Comment by WishMelz** [comment]
使用体验,后续修复吧.   要不你来改吧,到时候你提交一个pr,岂不美哉

**Comment by Coffee-kitten** [comment]
你好 老哥 我把你的帮助页面pr给了另一个项目 并作了修改 https://github.com/Coffee-kitten/picx
