### ISSUE TITLE
当仓库过多时，只能拉取最前面的几个

### ISSUE THREAD

**Issue by wineee** [WishMelz/imgurl#4]
![image](https://user-images.githubusercontent.com/22803888/223056181-236603a5-bb70-4a42-9d01-ad52901e8256.png)
我 fork 的仓库比较多，只能拉取 a/b/c/d 开头的前几十个，后面的仓库找不到

**Comment by WishMelz** [comment]
用自定义目录

**Comment by wineee** [comment]
自定义目录不能选仓库

**Comment by wineee** [comment]
![image](https://user-images.githubusercontent.com/22803888/224229449-f2724500-cad7-4045-a1d5-515bb019a5be.png)

**Comment by WishMelz** [comment]
不要选择fork的仓库，有问题

**Comment by WishMelz** [comment]
当初没考虑到那么多仓库，可能分页了，你自己改一下代码咯
